### ISSUE TITLE
TypeError: Cannot read property 'input' of undefined

### ISSUE THREAD

**Issue by smparthiban10** [Sharavanth/headoffice#100]
If enter the "Enter Data" button got the "Cannot read property 'input' of undefined" issue. It has in under the collection menu.
![err](https://cloud.githubusercontent.com/assets/26274769/24032861/36a21b44-0b10-11e7-8ea2-855d0ff68186.png)

**Comment by Sharavanth** [comment]
Currently being fixed in #111
