### ISSUE TITLE
Favourite icon has to be modified in list of collections menu

### ISSUE THREAD

**Issue by kfk12688** [Sharavanth/headoffice#98]
Favourite icon dosen't work properly in a single click. It has to be modified in list of collections menu and same problem occur in list of collections view page. 
![screenshot-localhost-3001-2017-03-17-12-03-11](https://cloud.githubusercontent.com/assets/23191491/24031809/a0bf7554-0b0a-11e7-8429-680359e1b71d.png)
![screenshot-localhost-3001-2017-03-17-12-10-26](https://cloud.githubusercontent.com/assets/23191491/24031830/c32b59c8-0b0a-11e7-8fbe-6694528a9a3e.png)

**Comment by Sharavanth** [comment]
This bug is reproducible in the following routes
- /collections
- /collections/:collectionName
