### ISSUE TITLE
Not able to check the checkbox

### ISSUE THREAD

**Issue by smparthiban10** [Sharavanth/headoffice#99]
Checkbox icon not working properly.Cannot able to check the checkbox icon. It has in under the general filters option.
![screenshot-localhost-3001-2017-03-17-12-18-17](https://cloud.githubusercontent.com/assets/26274769/24032160/8474aa7a-0b0c-11e7-9430-a942f56c62a8.png)

**Comment by Sharavanth** [comment]
Not a bug.... Due to improper value given in search bar
